import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Project, RoleId, Run } from "@appforge/core";
import { truncate } from "@appforge/core";
import type { ContextProvider } from "@appforge/orchestrator";
import { skillsPrompt } from "@appforge/storage";
import type { AssetService } from "./assets.ts";
import type { Store } from "./db/store.ts";
import type { LogService, MemoryService } from "./logs.ts";
import type { StorageManager } from "./storage.ts";

const CONTEXT_DIR = ".appforge/context";
const RECENT_LOGS = 5;
const MAX_LOG_CHARS = 200_000;

const CONTEXT_NOTE = `## Project context
AppForge keeps project knowledge for you in ${CONTEXT_DIR}/ (read-only, not committed):
- ${CONTEXT_DIR}/PROJECT_CONTEXT.md: project memory (decisions, conventions), every story so far with its outcome, and recent runs. Read it first.
- ${CONTEXT_DIR}/logs/: full logs of the most recent runs. Search them when you need to know what was tried before, why something failed, or what a reviewer asked for.
- ${CONTEXT_DIR}/images/: reference images for the current story, if any.`;

/** Gives every agent the project's skills, memory, history, logs and reference images. */
export class ProjectContextProvider implements ContextProvider {
  constructor(
    private readonly db: Store,
    private readonly storage: StorageManager,
    private readonly logs: LogService,
    private readonly memory: MemoryService,
    private readonly assets: AssetService,
  ) {}

  async systemAddendum(project: Project, role: RoleId): Promise<string> {
    const skills = await this.storage.skills.enabledFor(project.settings.skills);
    return [skillsPrompt(skills, role), CONTEXT_NOTE].filter(Boolean).join("\n\n");
  }

  async prepare(project: Project, run: Run, cwd: string): Promise<{ images: string[] }> {
    const dir = path.join(cwd, CONTEXT_DIR);
    await rm(dir, { recursive: true, force: true });
    await mkdir(path.join(dir, "logs"), { recursive: true });

    // Recent logs (newest first in the listing).
    const logFiles = await this.logs.list(project.id);
    for (const f of logFiles.slice(0, RECENT_LOGS)) {
      const text = await this.logs.get(project.id, f.name);
      if (text) await writeFile(path.join(dir, "logs", f.name), truncate(text, MAX_LOG_CHARS));
    }

    // Reference images of the current story.
    const images: string[] = [];
    const story = run.storyId ? this.db.getStory(run.storyId) : undefined;
    if (story?.images.length) {
      await mkdir(path.join(dir, "images"), { recursive: true });
      for (const [i, assetId] of story.images.entries()) {
        const asset = this.db.getAsset(assetId);
        const bytes = asset && (await this.assets.read(asset));
        if (!asset || !bytes) continue;
        const file = path.join(dir, "images", `${String(i + 1).padStart(2, "0")}-${asset.name.replace(/[^\w.-]+/g, "_")}`);
        await writeFile(file, bytes);
        images.push(file);
      }
    }

    // Files that ship with enabled skills.
    for (const skill of await this.storage.skills.enabledFor(project.settings.skills)) {
      for (const rel of skill.files) {
        const bytes = await this.storage.skills.readFile(skill.id, rel);
        if (!bytes) continue;
        const target = path.join(dir, "skills", skill.id, ...rel.split("/"));
        await mkdir(path.dirname(target), { recursive: true });
        await writeFile(target, bytes);
      }
    }

    await writeFile(path.join(dir, "PROJECT_CONTEXT.md"), await this.summary(project, run, logFiles.map((f) => f.name)));
    return { images };
  }

  private async summary(project: Project, run: Run, logNames: string[]): Promise<string> {
    const memory = (await this.memory.get(project.id)).trim();
    const stories = this.db.listStories(project.id);
    const runs = this.db.listRuns(project.id).slice(0, 15);
    const lines = [
      `# ${project.name} — project context`,
      "_Generated by AppForge before this agent turn. Read-only._",
      "",
      "## Project memory",
      memory || "(empty — the human can add decisions and conventions on the Memory tab)",
      "",
      "## Stories",
      ...(stories.length
        ? stories.map((s) => {
            const current = s.id === run.storyId ? " ← current" : "";
            return `- [${s.status}] ${s.title}${current}${s.outcome ? ` — ${s.outcome}` : ""}${s.plan ? `\n  Plan: ${s.plan.summary}` : ""}`;
          })
        : ["(none yet)"]),
      "",
      "## Recent runs (newest first)",
      ...runs.map((r) => `- ${r.createdAt.slice(0, 16)} ${r.mode} → ${r.status}${r.error ? ` (${truncate(r.error, 160)})` : ""}: ${truncate(r.brief.split("\n")[0] ?? "", 100)}`),
      "",
      "## Log files",
      logNames.length ? `Most recent ${Math.min(RECENT_LOGS, logNames.length)} are in logs/. All logs: ${logNames.join(", ")}` : "(no logs yet)",
    ];
    return `${lines.join("\n")}\n`;
  }
}
