import { readFile } from "node:fs/promises";
import path from "node:path";
import { slugify } from "@appforge/core";
import { ScriptedAdapter, type ScriptContext, type ScriptStep } from "./scripted.ts";

/**
 * "Demo" provider: plays every role with canned but structurally real output
 * (spec + task JSON, file edits inside the owned paths, JSON review verdicts,
 * test files, conflict resolution, report). Lets you watch a whole
 * pipeline/swarm run — branches, worktrees, approvals, merges — for free.
 * Enable with APPFORGE_DEMO=1.
 */
export function createDemoAdapter(): ScriptedAdapter {
  return new ScriptedAdapter(demoScript, "demo", "Demo (no account, canned output)");
}

export async function demoScript(ctx: ScriptContext): Promise<ScriptStep> {
  const delayMs = 400;
  switch (ctx.role) {
    case "architect":
      return architect(ctx.prompt, delayMs);
    case "coder":
      return coder(ctx, delayMs);
    case "reviewer":
      return {
        delayMs,
        text: '```json\n{"verdict": "approve", "summary": "Demo review: the change matches the task.", "issues": [{"severity": "nit", "message": "Consider adding a comment."}]}\n```',
      };
    case "test-author":
      return testAuthor(ctx, delayMs);
    case "integrator":
      return integrator(ctx, delayMs);
  }
}

function architect(prompt: string, delayMs: number): ScriptStep {
  const brief = section(prompt, "Brief") || "an app";
  const tasks = [
    {
      key: "backend-api",
      title: "Build the backend API",
      description: `REST endpoints for: ${brief.slice(0, 200)}`,
      area: "backend",
      dependsOn: [],
      files: ["backend/src/routes/**"],
    },
    {
      key: "auth",
      title: "Add authentication",
      description: "Token-based login endpoint and middleware.",
      area: "backend",
      dependsOn: [],
      files: ["backend/src/auth/**"],
    },
    {
      key: "frontend-ui",
      title: "Build the frontend UI",
      description: "Screens that call the API described in docs/openapi.yaml.",
      area: "frontend",
      dependsOn: [],
      files: ["frontend/src/features/**"],
    },
  ];
  return {
    delayMs,
    files: {
      "docs/SPEC.md": `# Spec\n\n## Brief\n\n${brief}\n\n## Tasks\n\n${tasks.map((t) => `- **${t.title}** — ${t.description}`).join("\n")}\n`,
      "docs/openapi.yaml": "openapi: 3.1.0\ninfo:\n  title: Demo API\n  version: 0.1.0\npaths:\n  /api/health:\n    get:\n      responses:\n        '200':\n          description: OK\n",
    },
    text: `Wrote docs/SPEC.md and docs/openapi.yaml.\n\n\`\`\`json\n${JSON.stringify({ summary: `Demo plan for: ${brief.slice(0, 120)}`, tasks }, null, 2)}\n\`\`\``,
  };
}

function coder(ctx: ScriptContext, delayMs: number): ScriptStep {
  const title = (/^## (?:Task|Request): (.+)$/m.exec(ctx.prompt)?.[1] ?? "change").trim();
  const owned = /You own these paths \(stay inside them\): (.+)$/m.exec(ctx.prompt)?.[1]?.split(",")[0]?.trim();
  const dir = owned ? owned.replace(/\/?\*\*.*$/, "").replace(/\/\*.*$/, "") : "appforge-demo";
  const fixing = /## Fix the following/.test(ctx.prompt);
  const file = `${dir || "."}/${slugify(title)}.ts`;
  return {
    delayMs,
    files: {
      [file]: `// ${title}\n// Generated by the AppForge demo provider${fixing ? " (after feedback)" : ""}.\nexport const feature = ${JSON.stringify(slugify(title))};\n`,
    },
    text: `${fixing ? "Addressed the feedback and updated" : "Implemented"} ${title} in ${file}.`,
  };
}

function testAuthor(ctx: ScriptContext, delayMs: number): ScriptStep {
  const title = (/^## Write tests for task: (.+)$/m.exec(ctx.prompt)?.[1] ?? "feature").trim();
  const unitDir = /in (\S+)\. Cover the behaviour/.exec(ctx.prompt)?.[1] ?? "tests";
  return {
    delayMs,
    files: { [`${unitDir.replace(/\/$/, "")}/${slugify(title)}.test.ts`]: `// Demo test for ${title}\n` },
    text: `Added tests for ${title}.`,
  };
}

async function integrator(ctx: ScriptContext, delayMs: number): Promise<ScriptStep> {
  if (ctx.prompt.includes("## Resolve merge conflicts")) {
    const files: Record<string, string> = {};
    for (const match of ctx.prompt.matchAll(/^- (.+)$/gm)) {
      const rel = match[1]?.trim();
      if (!rel) continue;
      const text = await readFile(path.join(ctx.cwd, rel), "utf8").catch(() => "");
      files[rel] = text.replace(/^(<<<<<<<|=======|>>>>>>>).*\n/gm, "");
    }
    return { delayMs, files, text: `Resolved conflicts in ${Object.keys(files).join(", ")} by keeping both sides.` };
  }
  return {
    delayMs,
    files: { "docs/REPORT.md": `# Integration report\n\n${section(ctx.prompt, "Write the integration report") || "All tasks merged."}\n` },
    text: "Wrote docs/REPORT.md. All demo tasks were merged.",
  };
}

function section(text: string, heading: string): string {
  const start = text.indexOf(`## ${heading}`);
  if (start === -1) return "";
  const rest = text.slice(start + heading.length + 3);
  const end = rest.indexOf("\n## ");
  return (end === -1 ? rest : rest.slice(0, end)).trim();
}
